### PR TITLE
fixed links to https://github.com/robolectric/robolectric-samples

### PR DESCRIPTION
**Pull request by mikosik**

### CODE REVIEW

**Comment by erd** [comment]
This should be fixed on master.

**Comment by mikosik** [comment]
> This should be fixed on master.

@erd 
I fixed it on `source` branch because this is the one marked as default in github.
Also `master` branch doesn't have any *.md files but only *.html files so I assumed that those html files are generated from *.md files.

I would suggest merging this pull-request to `source` branch (as obviously links are broken there) and based on that generate *.html files and commit them to `master`.

**Comment by erd** [comment]
Sorry, what I meant was, it was fixed in this commit: 0fca232bb2eb2ce2b64a8365d4c63a96a85dc1b7

I made that change before I realized that this PR existed :disappointed:

**Comment by mikosik** [comment]
> Sorry, what I meant was, it was fixed in this commit: 0fca232

That commit fixed links in readme.md only.
This pull requests fixes three others.
For example html that is live here http://robolectric.org/release-notes/ still has incorrect link to samples.

**Pull request closed without merging**
