### PR TITLE
Add --recurse-submodules for clone command

### PR DESCRIPTION
**Pull request by utzcoz**
Add `--recurse-submodules` for clone command.

cc @hoisie .

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @hoisie , maybe this PR needs your review. Thanks.

**Review by hoisie — APPROVED** [review]

**Comment by hoisie** [comment]
Feel free to click thr 'Rebase and Merge' after I approve PRS :)

**Comment by utzcoz** [comment]
> Feel free to click thr 'Rebase and Merge' after I approve PRS :) I started using rebase and Merge, especially for copybara commits.

Thanks for your trust.

**Comment by utzcoz** [comment]
Hi @hoisie, what about helping to merge this PR? Thanks. I don't have permission of this repo now.

**Pull request merged**
