### PR TITLE
Add docs for 4.6

### PR DESCRIPTION
**Pull request by utzcoz**
Following updating `robolectric.github.io` part of https://github.com/robolectric/robolectric/wiki/Performing-a-Release#release.

Fix: https://github.com/robolectric/robolectric.github.io/issues/88.

### CODE REVIEW

**Comment by utzcoz** [comment]
Hi @hoisie , could you help to review this PR? Thanks.

**Comment by utzcoz** [comment]
The javadoc is generated after I checkout `robolectric-4.6` tag.

**Comment by hoisie** [comment]
Thanks for doing this!

**Comment by utzcoz** [comment]
> Thanks for doing this!

Updating javadoc is very interesting :).

**Comment by hoisie** [comment]
Looks like the 'search' feature is broken for the 4.6 docs due to a Javadoc bug:
https://bugs.openjdk.java.net/browse/JDK-8215291

I believe Javadocs can only be built on JDK9 or JDK 12+.

**Comment by utzcoz** [comment]
> Looks like the 'search' feature is broken for the 4.6 docs due to a Javadoc bug:
> https://bugs.openjdk.java.net/browse/JDK-8215291
> 
> For instance, if you search and click on a result, you'll get a 404.
> 
> I believe Javadocs can only be built on JDK9 or JDK 12+.

I used JDK 11 to build it. I will update it with JDK 9 again to check search function.

**Comment by hoisie** [comment]
FYI I generally do:

PATH="/path/to/jdk9/bin:$PATH" ./gradlew clean aggregateDocs

**Comment by utzcoz** [comment]
> FYI I generally do:
> 
> PATH="/path/to/jdk9/bin:$PATH" ./gradlew clean aggregateDocs

The 4.7 uses new AGP needs JDK 11, I can try JDK 14 installed locally to test it. If it doesn't work, I will come back to JDK 9.

**Comment by utzcoz** [comment]
It's weird. The JDK 9 downloaded from openjdk.net has zip problem. The JDK 13, 14 caused another javadoc error, unmoduled tag. The JDK 10 doesn't work for me with can't fetch android reference. I am trying AdoptJDK.

**Comment by utzcoz** [comment]
Emm. JDK 10 is my problem, with wrong proxy. But it generates the same result as JDK 11. I will investigate this problem to find reason.

**Pull request merged**
