### PR TITLE
Add Robolectric 4.7 javadoc

### PR DESCRIPTION
**Pull request by utzcoz**

### CODE REVIEW

**Comment by utzcoz** [comment]
cc @hoisie .

**Comment by hoisie** [comment]
Awesome, thanks a lot for doing this.

**Comment by utzcoz** [comment]
> Awesome, thanks a lot for doing this.

:) I will test it again after deployed online.

**Comment by utzcoz** [comment]
Looks like online version works fine (http://robolectric.org/javadoc/4.7/org/robolectric/shadows/support/v4/package-summary.html).

**Pull request merged**
